PROGNAME = os.prg
ROM = os.img

RM = Rm

os.img: os.prg
	burnroms

os.prg: kern_asm.o kernel.o font.o
	ld -o os.prg kern_asm.o kernel.o font.o #crt0.o libc.a

kern_asm.o: kern_asm.s
	gen -L2 kern_asm.s

kernel.o: kernel.c types.h font.h
	cc68x -c kernel.c

font.o: font.c font.h types.h
	cc68x -c font.c

clean:
	!$(RM) $(PROGNAME) $(ROM) kern_asm.o kernel.o font.o
